//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAC.ERP.Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContractDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractDetail()
        {
            this.ContractPrices = new HashSet<ContractPrice>();
        }
    
        public int Id { get; set; }
        public int ContractId { get; set; }
        public int ItemNo { get; set; }
        public int ConsumerId { get; set; }
        public int CMSNo { get; set; }
        public int MaterialDescription { get; set; }
        public Nullable<int> QPLNo { get; set; }
        public int UACPartNo { get; set; }
        public Nullable<int> Temper { get; set; }
        public Nullable<int> Alloy { get; set; }
        public Nullable<decimal> MinLenght { get; set; }
        public Nullable<decimal> MaxLenght { get; set; }
        public Nullable<decimal> SectionWeight { get; set; }
        public Nullable<decimal> MinWallThickness { get; set; }
        public Nullable<decimal> MaxWallThickness { get; set; }
        public int ContractHeaderId { get; set; }
    
        public virtual ContractHeader ContractHeader { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractPrice> ContractPrices { get; set; }
    }
}
