//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAC.ERP.Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POHead
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POHead()
        {
            this.POLines = new HashSet<POLine>();
        }
    
        public int POHeadID { get; set; }
        public string OrderNo { get; set; }
        public Nullable<System.DateTime> CustomerOrderDate { get; set; }
        public string Currency { get; set; }
        public Nullable<int> PaymentTerms { get; set; }
        public Nullable<int> DeliveryTerms { get; set; }
        public int DeliveryAddress { get; set; }
        public Nullable<int> InsideSalesRep { get; set; }
        public int CustomerId { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> StatusDate { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<int> ContactPerson { get; set; }
        public Nullable<int> Plant { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual CustomerContact CustomerContact { get; set; }
        public virtual Term Term { get; set; }
        public virtual Term Term1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<POLine> POLines { get; set; }
    }
}
