//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAC.ERP.Sales.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POLine
    {
        public int POLineId { get; set; }
        public int POHeadPOHeadID { get; set; }
        public Nullable<int> LineNo { get; set; }
        public string Item { get; set; }
        public string CustomerPart { get; set; }
        public string Description { get; set; }
        public string Alloy { get; set; }
        public string Temper { get; set; }
        public Nullable<decimal> Length { get; set; }
        public string LenghtUOM { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string QuantityUOM { get; set; }
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string Remarks { get; set; }
        public Nullable<decimal> Stensile { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public string CMS { get; set; }
        public Nullable<bool> FAIRequired { get; set; }
        public string PackingInfo { get; set; }
        public string Oil { get; set; }
        public Nullable<int> UpperShipTolerance { get; set; }
        public Nullable<int> LowerShipTolerance { get; set; }
        public string ToleranceUOM { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> DeliveryAddress { get; set; }
    
        public virtual CustomerAddress CustomerAddress { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual POHead POHead { get; set; }
    }
}
