//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UAC.ERP.Sales.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Production2016Entities : DbContext
    {
        public Production2016Entities()
            : base("name=Production2016Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<CustomerAddress> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerContact> CustomerContacts { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<ContractDetail> ContractDetails { get; set; }
        public virtual DbSet<ContractHeader> ContractHeaders { get; set; }
        public virtual DbSet<ContractPrice> ContractPrices { get; set; }
        public virtual DbSet<POHead> POHeads { get; set; }
        public virtual DbSet<POLine> POLines { get; set; }
        public virtual DbSet<Term> Terms { get; set; }
        public virtual DbSet<TermType> TermTypes { get; set; }
    }
}
